### ISSUE TITLE
Issues with FSM

### ISSUE THREAD

**Issue by lonjil** [bl0x/learn-fpga-amaranth#5]
In part 05, `with m.FSM` is used, and `fsm.state` is used within the with block. However, this causes an error which states that FSM doesn't have a property `state`. If you try to access `fsm.state` *after* exiting the with block, it works.

Also, 05, but not 06 and later, lacks `domain="slow"` in the FSM constructor, which I think is incorrect.

**Comment by bl0x** [comment]
Thanks for pointing out these things!

There was a breaking change a while back that makes `fsm.state` inaccessible inside the FSM context. (https://github.com/amaranth-lang/amaranth/pull/1164/commits/a7c649e9d315d91d8a8380bb7ed17cfcf780a08d)

Also, `domain="slow"` is indeed missing.

It looks like I have a bit of work to do to bring this repo back up to speed with Amaranth HDL 0.5.
